schema-version: 2.0.2

package:
  name: cass-config-builder

advisories:
  - id: CVE-2024-22871
    aliases:
      - GHSA-vr64-r9qj-h27f
    events:
      - timestamp: 2024-03-03T07:34:27Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: cass-config-builder
            componentID: 03e9e067c96e25ef
            componentName: clojure
            componentVersion: 1.10.1
            componentType: java-archive
            componentLocation: /usr/local/bin/cass-config-builder-1.0.8-20240131-all.jar
            scanner: grype
      - timestamp: 2024-03-15T00:35:51Z
        type: fixed
        data:
          fixed-version: 1.0.8-r3
