schema-version: 2.0.2

package:
  name: configurable-http-proxy

advisories:
  - id: CGA-q66j-qggf-9r53
    aliases:
      - CVE-2023-26159
      - GHSA-jchw-25xp-jwwc
    events:
      - timestamp: 2024-02-18T07:19:23Z
        type: fixed
        data:
          fixed-version: 4.6.1-r1

  - id: CGA-7g4q-75vq-228c
    aliases:
      - CVE-2024-28849
      - GHSA-cxjh-pqwp-8mfp
    events:
      - timestamp: 2024-04-05T07:52:00Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: configurable-http-proxy
            componentID: 97fc8d32a4089bab
            componentName: follow-redirects
            componentVersion: 1.15.5
            componentType: npm
            componentLocation: /srv/configurable-http-proxy/node_modules/follow-redirects/package.json
            scanner: grype
