schema-version: 2.0.2

package:
  name: ingress-nginx-controller-1.10

advisories:
  - id: CGA-44p9-q59x-hfv8
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-05T19:28:22Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.10
            componentID: e80cc1ad1fe528d8
            componentName: golang.org/x/oauth2
            componentVersion: v0.21.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-ingress-controller
            scanner: grype

  - id: CGA-96jc-h6m8-42q8
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2025-03-05T19:28:21Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.10
            componentID: d7316375d0a83ac6
            componentName: golang.org/x/net
            componentVersion: v0.26.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-ingress-controller
            scanner: grype

  - id: CGA-fp75-mrc8-pvr5
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2025-03-05T19:28:24Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.10
            componentID: 8bbe4067655b3255
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/nginx-dbg
            scanner: grype

  - id: CGA-hjjv-mfcc-p89p
    aliases:
      - CVE-2024-45310
      - GHSA-jfvp-7x6p-h2pv
    events:
      - timestamp: 2025-03-05T19:28:22Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.10
            componentID: dc13049969aa11e2
            componentName: github.com/opencontainers/runc
            componentVersion: v1.1.13
            componentType: go-module
            componentLocation: /usr/bin/nginx-ingress-controller
            scanner: grype

  - id: CGA-rfrv-7fcf-mccp
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2025-03-05T19:28:26Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.10
            componentID: 8bbe4067655b3255
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/nginx-dbg
            scanner: grype

  - id: CGA-vmx2-6vj6-p7rj
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2025-03-05T19:28:25Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.10
            componentID: 8bbe4067655b3255
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/nginx-dbg
            scanner: grype
