schema-version: 2.0.2

package:
  name: ingress-nginx

advisories:
  - id: CVE-2022-41741
    aliases:
      - GHSA-3v5h-538g-pr7g
    events:
      - timestamp: 2024-02-14T12:28:57Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx
            componentID: dfa4840085fbd94a
            componentName: nginx
            componentVersion: 1.21.6
            componentType: binary
            componentLocation: /usr/local/nginx/sbin/nginx
            scanner: grype

  - id: CVE-2022-41742
    aliases:
      - GHSA-wj45-j4gh-fm3x
    events:
      - timestamp: 2024-02-14T12:28:57Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx
            componentID: dfa4840085fbd94a
            componentName: nginx
            componentVersion: 1.21.6
            componentType: binary
            componentLocation: /usr/local/nginx/sbin/nginx
            scanner: grype

  - id: CVE-2023-44487
    aliases:
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2024-02-14T12:28:57Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx
            componentID: dfa4840085fbd94a
            componentName: nginx
            componentVersion: 1.21.6
            componentType: binary
            componentLocation: /usr/local/nginx/sbin/nginx
            scanner: grype
