schema-version: 2.0.2

package:
  name: nats-server-config-reloader

advisories:
  - id: CGA-cpmv-72cr-q8pc
    aliases:
      - CVE-2025-47910
      - GHSA-8pjc-487g-w6p2
    events:
      - timestamp: 2025-09-24T12:38:56Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nats-server-config-reloader
            componentID: 040e8a960cfbc3a1
            componentName: stdlib
            componentVersion: go1.25.0
            componentType: go-module
            componentLocation: /usr/bin/nats-server-config-reloader
            scanner: grype
      - timestamp: 2025-09-24T22:56:43Z
        type: fixed
        data:
          fixed-version: 0.19.2-r1

  - id: CGA-fqvq-j954-6792
    aliases:
      - CVE-2025-47907
      - GHSA-j5pm-7495-qmr3
    events:
      - timestamp: 2025-08-09T15:19:25Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nats-server-config-reloader
            componentID: 94a2cfb342f17061
            componentName: stdlib
            componentVersion: go1.24.5
            componentType: go-module
            componentLocation: /usr/bin/nats-server-config-reloader
            scanner: grype
      - timestamp: 2025-08-10T11:13:06Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Govulncheck found no affected symbols in the scanned Go binaries.
