schema-version: 2.0.2

package:
  name: prometheus-podman-exporter

advisories:
  - id: CGA-6395-xhp7-85w4
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T12:29:00Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-podman-exporter
            componentID: 3c6e36b551d6577b
            componentName: golang.org/x/crypto
            componentVersion: v0.26.0
            componentType: go-module
            componentLocation: /usr/bin/podman_exporter
            scanner: grype
