schema-version: 2.0.2

package:
  name: prometheus-3.5

advisories:
  - id: CGA-vhf6-3gh3-9c69
    aliases:
      - GHSA-fv92-fjc5-jj9h
    events:
      - timestamp: 2025-07-16T05:30:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.5
            componentID: 165ae65eb2ae9a93
            componentName: github.com/go-viper/mapstructure/v2
            componentVersion: v2.2.1
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype
      - timestamp: 2025-07-17T08:49:20Z
        type: fixed
        data:
          fixed-version: 3.5.0-r1
