schema-version: 2.0.2

package:
  name: prometheus-3.5

advisories:
  - id: CGA-cx29-58pp-hxjm
    aliases:
      - CVE-2025-47907
      - GHSA-j5pm-7495-qmr3
    events:
      - timestamp: 2025-08-09T20:23:20Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.5
            componentID: 101bfb8e41eb1227
            componentName: stdlib
            componentVersion: go1.24.5
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype

  - id: CGA-p769-wcv6-r8pm
    aliases:
      - CVE-2025-54388
      - GHSA-x4rx-4gw3-53p4
    events:
      - timestamp: 2025-07-30T07:42:19Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.5
            componentID: 6cd2927eaab164c8
            componentName: github.com/docker/docker
            componentVersion: v28.2.2+incompatible
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype
      - timestamp: 2025-07-30T09:35:50Z
        type: fixed
        data:
          fixed-version: 3.5.0-r2

  - id: CGA-vhf6-3gh3-9c69
    aliases:
      - GHSA-fv92-fjc5-jj9h
    events:
      - timestamp: 2025-07-16T05:30:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.5
            componentID: 165ae65eb2ae9a93
            componentName: github.com/go-viper/mapstructure/v2
            componentVersion: v2.2.1
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype
      - timestamp: 2025-07-17T08:49:20Z
        type: fixed
        data:
          fixed-version: 3.5.0-r1
