schema-version: "2"

package:
  name: py3-configobj

advisories:
  - id: CGA-9r88-r9jr-p44c
    aliases:
      - CVE-2023-26112
      - GHSA-c33w-24p9-8m24
    events:
      - timestamp: 2023-07-21T12:41:52Z
        type: false-positive-determination
        data:
          type: vulnerability-record-analysis-contested
          note: The maintainers correctly deemed this to not be a vulnerability given it requires the system operator to enter the incorrect value.
