schema-version: 2.0.2

package:
  name: skaffold

advisories:
  - id: CVE-2023-33199
    aliases:
      - GHSA-frqx-jfcm-6jjr
    events:
      - timestamp: 2023-08-02T17:03:24Z
        type: detection
        data:
          type: manual
      - timestamp: 2023-08-02T17:04:18Z
        type: fixed
        data:
          fixed-version: 2.6.2-r1

  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-15T20:48:25Z
        type: fixed
        data:
          fixed-version: 2.8.0-r4

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-15T20:48:33Z
        type: fixed
        data:
          fixed-version: 2.8.0-r4

  - id: CVE-2023-44487
    aliases:
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-15T20:48:42Z
        type: fixed
        data:
          fixed-version: 2.8.0-r4

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:37:51Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:37:52Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T08:01:46Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T08:01:40Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CVE-2023-46737
    aliases:
      - GHSA-vfp6-jrw2-99g9
    events:
      - timestamp: 2024-01-13T07:21:10Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d847741dbb3482ad
            componentName: github.com/sigstore/cosign/v2
            componentVersion: v2.0.3-0.20230523133326-0544abd8fc8a
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-01-14T11:46:53Z
        type: fixed
        data:
          fixed-version: 2.10.0-r2

  - id: CVE-2024-21626
    aliases:
      - GHSA-xr7r-f8xq-vfvv
    events:
      - timestamp: 2024-02-01T12:07:34Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: de84c0dcbb1276ab
            componentName: github.com/opencontainers/runc
            componentVersion: v1.1.7
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-11T12:48:47Z
        type: pending-upstream-fix
        data:
          note: Upgrading runc to a non-vulnerable version creates conflicts with other old dependencies required by skaffold such as go.opentelemetry.io/otel which is using v1.15.0.

  - id: CVE-2024-23650
    aliases:
      - GHSA-9p26-698r-w4hx
    events:
      - timestamp: 2024-02-01T12:07:30Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d0c01f359cccfed1
            componentName: github.com/moby/buildkit
            componentVersion: v0.11.6
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-13T00:18:51Z
        type: pending-upstream-fix
        data:
          note: Upgrading buildkit to a non-vulnerable version requires to bump github.com/docker/docker to v25.0.3 (currently using v24.0.7) and as a consequence needs multiple code changes to adapt the source code to this new version.

  - id: CVE-2024-23651
    aliases:
      - GHSA-m3r6-h7wv-7xxv
    events:
      - timestamp: 2024-02-01T12:07:31Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d0c01f359cccfed1
            componentName: github.com/moby/buildkit
            componentVersion: v0.11.6
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-13T00:17:52Z
        type: pending-upstream-fix
        data:
          note: Upgrading buildkit to a non-vulnerable version requires to bump github.com/docker/docker to v25.0.3 (currently using v24.0.7) and as a consequence needs multiple code changes to adapt the source code to this new version.

  - id: CVE-2024-23652
    aliases:
      - GHSA-4v98-7qmw-rqr8
    events:
      - timestamp: 2024-02-01T12:07:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d0c01f359cccfed1
            componentName: github.com/moby/buildkit
            componentVersion: v0.11.6
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-13T00:16:41Z
        type: pending-upstream-fix
        data:
          note: Upgrading buildkit to a non-vulnerable version requires to bump github.com/docker/docker to v25.0.3 (currently using v24.0.7) and as a consequence needs multiple code changes to adapt the source code to this new version.

  - id: CVE-2024-23653
    aliases:
      - GHSA-wr6v-9f75-vh2g
    events:
      - timestamp: 2024-02-01T12:07:32Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d0c01f359cccfed1
            componentName: github.com/moby/buildkit
            componentVersion: v0.11.6
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-11T12:50:32Z
        type: pending-upstream-fix
        data:
          note: Upgrading buildkit to a non-vulnerable version requires to bump github.com/docker/docker to v25.0.3 (currently using v24.0.7) and as a consequence needs multiple code changes to adapt the source code to this new version.

  - id: CVE-2024-24557
    aliases:
      - GHSA-xw73-rw38-6vjc
    events:
      - timestamp: 2024-03-25T14:36:15Z
        type: fixed
        data:
          fixed-version: 2.10.1-r3

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T08:01:38Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T08:01:42Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T08:01:44Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-15T23:37:42Z
        type: fixed
        data:
          fixed-version: 2.10.1-r2

  - id: CVE-2024-28180
    aliases:
      - GHSA-c5q2-7r4c-mv6g
    events:
      - timestamp: 2024-03-08T07:26:24Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: de3b754d23e693af
            componentName: gopkg.in/go-jose/go-jose.v2
            componentVersion: v2.6.1
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-03-15T23:37:42Z
        type: fixed
        data:
          fixed-version: 2.10.1-r2

  - id: GHSA-7ww5-4wqc-m92c
    events:
      - timestamp: 2024-01-13T07:21:09Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: 3644179ba8ac321e
            componentName: github.com/containerd/containerd
            componentVersion: v1.7.2
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-01-14T11:45:35Z
        type: pending-upstream-fix
        data:
          note: This vulnerability requires changes in the upstream code to support a containerd version with the fixed vulnerability.

  - id: GHSA-9763-4f94-gfch
    events:
      - timestamp: 2024-01-10T01:50:57Z
        type: fixed
        data:
          fixed-version: 2.10.0-r1

  - id: GHSA-jq35-85cj-fj4p
    events:
      - timestamp: 2024-01-13T07:21:10Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: 0d043b703d8b05df
            componentName: github.com/docker/docker
            componentVersion: v24.0.5+incompatible
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-01-14T11:47:16Z
        type: fixed
        data:
          fixed-version: 2.10.0-r2
