schema-version: 2.0.2

package:
  name: skaffold

advisories:
  - id: CGA-22jm-fmjr-77q6
    aliases:
      - CVE-2024-24557
      - GHSA-xw73-rw38-6vjc
    events:
      - timestamp: 2024-03-25T14:36:15Z
        type: fixed
        data:
          fixed-version: 2.10.1-r3

  - id: CGA-344h-5273-2qm3
    aliases:
      - CVE-2024-23653
      - GHSA-wr6v-9f75-vh2g
    events:
      - timestamp: 2024-02-01T12:07:32Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d0c01f359cccfed1
            componentName: github.com/moby/buildkit
            componentVersion: v0.11.6
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-11T12:50:32Z
        type: pending-upstream-fix
        data:
          note: Upgrading buildkit to a non-vulnerable version requires to bump github.com/docker/docker to v25.0.3 (currently using v24.0.7) and as a consequence needs multiple code changes to adapt the source code to this new version.
      - timestamp: 2024-04-03T16:46:43Z
        type: fixed
        data:
          fixed-version: 2.11.0-r0

  - id: CGA-375r-pg5p-c2hw
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T16:17:23Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: a10ab0b35f537736
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-09-12T20:19:13Z
        type: fixed
        data:
          fixed-version: 2.13.2-r1

  - id: CGA-3rxv-jgqg-cjhv
    aliases:
      - CVE-2024-51744
      - GHSA-29wx-vh33-7x7r
    events:
      - timestamp: 2024-11-05T09:23:19Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: 7a5a011286efd8c1
            componentName: github.com/golang-jwt/jwt/v4
            componentVersion: v4.5.0
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-11-05T13:24:55Z
        type: fixed
        data:
          fixed-version: 2.13.2-r2

  - id: CGA-4rrj-jwj8-r753
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T07:44:49Z
        type: fixed
        data:
          fixed-version: 2.12.0-r1

  - id: CGA-4v89-2cfq-fc44
    aliases:
      - GHSA-jq35-85cj-fj4p
    events:
      - timestamp: 2024-01-13T07:21:10Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: 0d043b703d8b05df
            componentName: github.com/docker/docker
            componentVersion: v24.0.5+incompatible
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-01-14T11:47:16Z
        type: fixed
        data:
          fixed-version: 2.10.0-r2

  - id: CGA-58x8-xchw-fh5f
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T07:44:42Z
        type: fixed
        data:
          fixed-version: 2.12.0-r1

  - id: CGA-5j78-48fp-qfr4
    aliases:
      - CVE-2023-46737
      - GHSA-vfp6-jrw2-99g9
    events:
      - timestamp: 2024-01-13T07:21:10Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d847741dbb3482ad
            componentName: github.com/sigstore/cosign/v2
            componentVersion: v2.0.3-0.20230523133326-0544abd8fc8a
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-01-14T11:46:53Z
        type: fixed
        data:
          fixed-version: 2.10.0-r2

  - id: CGA-65wm-fjc7-39qm
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T15:09:21Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: dd81b3914fea0b9e
            componentName: golang.org/x/net
            componentVersion: v0.25.0
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-12-20T04:07:48Z
        type: fixed
        data:
          fixed-version: 2.13.2-r4

  - id: CGA-7rcq-56wv-w7g4
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T11:45:20Z
        type: fixed
        data:
          fixed-version: 2.12.0-r2

  - id: CGA-9c9r-rv7c-jw89
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T08:01:38Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CGA-9rhv-6x5x-p3wh
    aliases:
      - CVE-2024-23652
      - GHSA-4v98-7qmw-rqr8
    events:
      - timestamp: 2024-02-01T12:07:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d0c01f359cccfed1
            componentName: github.com/moby/buildkit
            componentVersion: v0.11.6
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-13T00:16:41Z
        type: pending-upstream-fix
        data:
          note: Upgrading buildkit to a non-vulnerable version requires to bump github.com/docker/docker to v25.0.3 (currently using v24.0.7) and as a consequence needs multiple code changes to adapt the source code to this new version.
      - timestamp: 2024-04-03T16:46:16Z
        type: fixed
        data:
          fixed-version: 2.11.0-r0

  - id: CGA-9vcv-g7q6-q9hj
    aliases:
      - GHSA-9763-4f94-gfch
    events:
      - timestamp: 2024-01-10T01:50:57Z
        type: fixed
        data:
          fixed-version: 2.10.0-r1

  - id: CGA-c2wj-qvw6-v5cc
    aliases:
      - CVE-2023-44487
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-15T20:48:42Z
        type: fixed
        data:
          fixed-version: 2.8.0-r4

  - id: CGA-c8wc-jq6c-f7cr
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T08:01:40Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CGA-ghc9-hpx3-hf9c
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T10:08:03Z
        type: fixed
        data:
          fixed-version: 2.11.1-r3

  - id: CGA-h7hc-hpg4-fcx8
    aliases:
      - CVE-2024-29903
      - GHSA-95pr-fxf5-86gv
    events:
      - timestamp: 2024-04-13T07:21:39Z
        type: fixed
        data:
          fixed-version: 2.11.1-r1

  - id: CGA-h86r-rp6w-gq5r
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-15T23:37:42Z
        type: fixed
        data:
          fixed-version: 2.10.1-r2

  - id: CGA-h9rw-mjh3-hcv3
    aliases:
      - GHSA-7ww5-4wqc-m92c
    events:
      - timestamp: 2024-01-13T07:21:09Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: 3644179ba8ac321e
            componentName: github.com/containerd/containerd
            componentVersion: v1.7.2
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-01-14T11:45:35Z
        type: pending-upstream-fix
        data:
          note: This vulnerability requires changes in the upstream code to support a containerd version with the fixed vulnerability.
      - timestamp: 2024-04-03T16:46:43Z
        type: fixed
        data:
          fixed-version: 2.11.0-r0

  - id: CGA-hp98-6xmw-2qwf
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-15T20:48:33Z
        type: fixed
        data:
          fixed-version: 2.8.0-r4

  - id: CGA-hpfp-4ff7-27r4
    aliases:
      - CVE-2024-23651
      - GHSA-m3r6-h7wv-7xxv
    events:
      - timestamp: 2024-02-01T12:07:31Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d0c01f359cccfed1
            componentName: github.com/moby/buildkit
            componentVersion: v0.11.6
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-13T00:17:52Z
        type: pending-upstream-fix
        data:
          note: Upgrading buildkit to a non-vulnerable version requires to bump github.com/docker/docker to v25.0.3 (currently using v24.0.7) and as a consequence needs multiple code changes to adapt the source code to this new version.
      - timestamp: 2024-04-03T16:46:44Z
        type: fixed
        data:
          fixed-version: 2.11.0-r0

  - id: CGA-hxcc-jchc-2c3j
    aliases:
      - CVE-2023-33199
      - GHSA-frqx-jfcm-6jjr
    events:
      - timestamp: 2023-08-02T17:03:24Z
        type: detection
        data:
          type: manual
      - timestamp: 2023-08-02T17:04:18Z
        type: fixed
        data:
          fixed-version: 2.6.2-r1

  - id: CGA-jm2j-3vfm-fp5f
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T08:01:42Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CGA-mhh9-9wv9-hfxg
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:37:51Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-mph8-pj2w-hg4g
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T08:01:46Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CGA-p27g-5r49-56m8
    aliases:
      - CVE-2024-29902
      - GHSA-88jx-383q-w4qc
    events:
      - timestamp: 2024-04-13T07:21:30Z
        type: fixed
        data:
          fixed-version: 2.11.1-r1

  - id: CGA-p422-qhh6-33f6
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:37:52Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-q5pr-fg2h-p7p3
    aliases:
      - CVE-2024-28180
      - GHSA-c5q2-7r4c-mv6g
    events:
      - timestamp: 2024-03-08T07:26:24Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: de3b754d23e693af
            componentName: gopkg.in/go-jose/go-jose.v2
            componentVersion: v2.6.1
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-03-15T23:37:42Z
        type: fixed
        data:
          fixed-version: 2.10.1-r2

  - id: CGA-qc23-8j6m-xxxc
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T22:23:42Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: 7e55536f5e620e73
            componentName: golang.org/x/crypto
            componentVersion: v0.22.0
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-12-13T21:41:31Z
        type: fixed
        data:
          fixed-version: 2.13.2-r3

  - id: CGA-qf6w-j26v-4m9r
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T16:17:13Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: a10ab0b35f537736
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-09-12T20:19:13Z
        type: fixed
        data:
          fixed-version: 2.13.2-r1

  - id: CGA-qv9p-29m5-xqpx
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T08:01:44Z
        type: fixed
        data:
          fixed-version: 2.10.1-r1

  - id: CGA-r665-2835-4pc9
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-20T18:03:22Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: a52296fd0cbe5244
            componentName: golang.org/x/net
            componentVersion: v0.22.0
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-04-23T10:07:30Z
        type: fixed
        data:
          fixed-version: 2.11.1-r2

  - id: CGA-rp4c-746f-jv9f
    aliases:
      - CVE-2024-21626
      - GHSA-xr7r-f8xq-vfvv
    events:
      - timestamp: 2024-02-01T12:07:34Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: de84c0dcbb1276ab
            componentName: github.com/opencontainers/runc
            componentVersion: v1.1.7
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-11T12:48:47Z
        type: pending-upstream-fix
        data:
          note: Upgrading runc to a non-vulnerable version creates conflicts with other old dependencies required by skaffold such as go.opentelemetry.io/otel which is using v1.15.0.
      - timestamp: 2024-04-03T16:46:42Z
        type: fixed
        data:
          fixed-version: 2.11.0-r0

  - id: CGA-rw49-59gp-gfv9
    aliases:
      - CVE-2024-23650
      - GHSA-9p26-698r-w4hx
    events:
      - timestamp: 2024-02-01T12:07:30Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: d0c01f359cccfed1
            componentName: github.com/moby/buildkit
            componentVersion: v0.11.6
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-02-13T00:18:51Z
        type: pending-upstream-fix
        data:
          note: Upgrading buildkit to a non-vulnerable version requires to bump github.com/docker/docker to v25.0.3 (currently using v24.0.7) and as a consequence needs multiple code changes to adapt the source code to this new version.
      - timestamp: 2024-04-03T16:46:42Z
        type: fixed
        data:
          fixed-version: 2.11.0-r0

  - id: CGA-v4cq-jf85-m8rx
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-15T20:48:25Z
        type: fixed
        data:
          fixed-version: 2.8.0-r4

  - id: CGA-v6g5-rvm7-p5jv
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T16:17:33Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: a10ab0b35f537736
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-09-12T20:19:12Z
        type: fixed
        data:
          fixed-version: 2.13.2-r1

  - id: CGA-x324-7v9x-m377
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T10:07:59Z
        type: fixed
        data:
          fixed-version: 2.11.1-r3

  - id: CGA-xhhw-6jmq-w8vc
    aliases:
      - CVE-2020-8559
      - GHSA-33c5-9fx5-fvjm
    events:
      - timestamp: 2024-04-25T13:41:07Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: 22f4ece1336e1118
            componentName: k8s.io/apimachinery
            componentVersion: v0.28.3
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype

  - id: CGA-xmcc-q53c-4rp3
    aliases:
      - CVE-2024-41110
      - GHSA-v23v-6jw2-98fq
    events:
      - timestamp: 2024-07-31T10:07:17Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: 2b08cdd71e37673f
            componentName: github.com/docker/docker
            componentVersion: v25.0.5+incompatible
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype
      - timestamp: 2024-08-01T18:28:12Z
        type: pending-upstream-fix
        data:
          note: It require some code changes and bump other dependencies that also need code changes to be able to bump this dependency.
