schema-version: 2.0.2

package:
  name: traefik-3.3

advisories:
  - id: CGA-cgqm-p5gm-9xxj
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T15:40:04Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.3
            componentID: 250d5566dc9da0ad
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2025-02-09T06:09:04Z
        type: fixed
        data:
          fixed-version: 3.3.3-r1
