issuer: https://accounts.google.com

# staging-images: advisory-ing-annok33bkfnx8xg7k@staging-enforce-cd1e.iam.gserviceaccount.com (112522501528385689106)
# prod-images: advisory-ing-xi53h6933zlnd2469@prod-enforce-fabc.iam.gserviceaccount.com (108967221351835873845)
subject_pattern: "(112522501528385689106|108967221351835873845)"

# This service needs to clone the advisories repo to import the existing advisories to a db.
permissions:
  contents: read
