issuer: https://accounts.google.com

# staging-enforce: gh-advisory-push-listener@staging-enforce-cd1e.iam.gserviceaccount.com (102452257683855765349)
# prod-enforce: gh-advisory-push-listener@prod-enforce-fabc.iam.gserviceaccount.com (109564263906729966224)
subject_pattern: "(102452257683855765349|109564263906729966224)"

permissions:
  contents: read
