issuer: https://accounts.google.com

# staging-enforce: wolfi-gh-push-listener@staging-enforce-cd1e.iam.gserviceaccount.com (101094128262755427544)
# prod-enforce: 
subject_pattern: "(101094128262755427544)"

permissions:
  contents: read
