issuer: https://accounts.google.com

# staging-enforce: gh-advisory-push-listener@staging-enforce-cd1e.iam.gserviceaccount.com (102452257683855765349)
# prod-enforce: TBD 
subject_pattern: "(102452257683855765349)"

permissions:
  contents: read
