issuer: https://token.actions.githubusercontent.com
subject: repo:wolfi-dev/advisories:ref:refs/heads/main
claim_pattern:
  workflow_ref: wolfi-dev/advisories/.github/workflows/delete-old-branches.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: read
