issuer: https://accounts.google.com

# prod-images: bot-triageolwolfi@staging-enforce-cd1e.iam.gserviceaccount.com
# bot-triageolwolfi@prod-enforce-fabc.iam.gserviceaccount.com
subject_pattern: "(102425108416137555121|108215247871814150708)"

permissions:
  pull_requests: write
  contents: write
  workflows: write
