issuer: https://accounts.google.com

# lifecycle-adv-ing-d642yk3csqr@hector-cg-dev-chainguard-dev.iam.gserviceaccount.com
subject_pattern: "(105719398959163122807)"

# This service needs to clone the advisories repo to import the existing advisories to a db.
permissions:
  contents: read
