issuer: https://accounts.google.com

# staging-images: cve-eol-sa@staging-images-183e.iam.gserviceaccount.com (105584575053184700385)
# prod-images: cve-eol-sa@prod-images-c6e5.iam.gserviceaccount.com ()
subject_pattern: "(105584575053184700385)"

permissions:
  pull_requests: write
  contents: write
  workflows: write
