issuer: https://accounts.google.com

# staging-images: cve-fix-sa@staging-images-183e.iam.gserviceaccount.com (110841568661625776456)
# prod-images: cve-fix-sa@prod-images-c6e5.iam.gserviceaccount.com (116759360681829295530)
subject_pattern: "(110841568661625776456|116759360681829295530)"

permissions:
  pull_requests: write
  contents: write
  workflows: write
