issuer: https://accounts.google.com

# staging-images: cve-triage-sa@staging-images-183e.iam.gserviceaccount.com (117226091809388380557)
# prod-images: cve-triage-sa@prod-images-c6e5.iam.gserviceaccount.com (116657797117571590580)
subject_pattern: "(116657797117571590580|117226091809388380557)"

# This service interacts with the advisory repository and creates pull requests with suggested changes to the existing files.
permissions:
  pull_requests: write
  contents: write
  workflows: write
