issuer: https://accounts.google.com

# prod-images: bot-triageolwolfi@staging-enforce-cd1e.iam.gserviceaccount.com
# bot-triageolwolfi@prod-enforce-fabc.iam.gserviceaccount.com
subject: "(102425108416137555121|108215247871814150708)"

permissions:
  contents: read 
