issuer: https://accounts.google.com

# prod-images: lifecycle-eol-mover@prod-images-c6e5.iam.gserviceaccount.com
subject: "105314035764875766195"

permissions:
  contents: read # to clone the repository
