issuer: https://accounts.google.com

# eol-cve-triage-tvw0l8pfys6ar7e@staging-enforce-cd1e.iam.gserviceaccount.com
# eol-cve-triage-ukbn1lwavqhiozn@prod-enforce-fabc.iam.gserviceaccount.com
subject_pattern: "(101250437316036373382|112057240867162796263)"

permissions:
  pull_requests: write
  contents: write
  workflows: write
