issuer: https://accounts.google.com

# lifecycle-adv-ing-d642yk3csqr@hector-cg-dev-chainguard-dev.iam.gserviceaccount.com
# lifecycle-adv-ing-fdhrtnokll5@staging-enforce-cd1e.iam.gserviceaccount.com
subject_pattern: "(101484292943470541224|105719398959163122807)"

# This service needs to clone the advisories repo to import the existing advisories to a db.
permissions:
  contents: read
